services:
  windows:
    image: dockurr/windows
    container_name: komorebi-test
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "4"
    devices:
      - /dev/kvm
    cap_add:
      - NET_ADMIN
    ports:
      - "8006:8006"
      - "3389:3389"
    volumes:
      - ./:/shared
      - win-storage:/storage
    stop_grace_period: 120s

volumes:
  win-storage:
